### ISSUE TITLE
POST

### ISSUE THREAD

**Issue by jtgreen** [dirkweissenborn/ctakes-server#1]
This is great! I've been meaning to do this for awhile. This is a big help!

Any plan to make this accept larger documents with post commands? 

Thanks!

**Comment by dirkweissenborn** [comment]
POST is already working, just didn't give an example. Just post the document as a string to the server. Give it a try.

**Comment by jtgreen** [comment]
This is wonderful work, thank you.As I understand it, it simply runs the uima pipeline in whatever desc file an simply deploys the cas as a json restful output, correct? Just sitting on top of ctakes? Or does it do special post processing?  Thanks  



On May 3, 2016 at 01:19:58 MDT, Dirk Weissenborn <notifications@github.com> wrote:Closed #1.  —You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by dirkweissenborn** [comment]
No special post processing. Keys are taken directly from the CAS. It takes whatever desc your feeding it.
