### ISSUE TITLE
desc/path/to/desc.xml

### ISSUE THREAD

**Issue by leej35** [dirkweissenborn/ctakes-server#2]
Hi, I am trying to follow the instruction to run ctakes as a server.

Can I know which desc.xml in the readme.md tutorial?

Thanks,
Jeongmin

**Comment by dirkweissenborn** [comment]
"[...]desc.xml"s come with cTakes. They are the UIMA descriptors used for setting up pipelines.  You can for example use the "desc/ctakes-ytex-uima/desc/analysis_engine/AggregatePlaintextUMLSProcessor.xml" as mentioned in the recommendations.
