### ISSUE TITLE
Could not find or load main class de.dfki.lt.ctakes.Server

### ISSUE THREAD

**Issue by atuls2** [dirkweissenborn/ctakes-server#6]
I am trying to run the project and completed each and every step.

while i am running this command 

java -Dctakes.umlsuser=myuser -Dctakes.umlspw=mypass -Xmx3g -cp target/ctakes-server-0.1.jar:resources/ de.dfki.lt.ctakes.Server localhost 9999 desc/ctakes-clinical-pipeline/desc/analysis_engine/AggregatePlaintextFastUMLSProcessor.xml

The error occurs as:

Error: Could not find or load main class de.dfki.lt.ctakes.Server

Please Help

**Comment by Michael-M-Judd** [comment]
Hey @atuls2 ! I'm having the same issue. Did you ever end up figuring out why?

I have a feeling it has something to do with the fact I'm on a Windows machine and it looks like the majority of the project was developed in Linux.

Thanks!

**Comment by atuls2** [comment]
Hey @Michael-M-Judd Michael, Try replacing ":" with ; in the line

java -Dctakes.umlsuser=myuser -Dctakes.umlspw=mypass -Xmx3g -cp target/**ctakes-server-0.1.jar;resources/** de.dfki.lt.ctakes.Server localhost 9999 desc/ctakes-clinical-pipeline/desc/analysis_engine/AggregatePlaintextFastUMLSProcessor.xml


the program will work.


Regards:
Atul

**Comment by Michael-M-Judd** [comment]
It worked, thanks!
